config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  root "home#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "articles" => "articles#index"
  post "articles" => "articles#new"
  get "articles/create" =>"articles#create"
  get "article/:id" => "articles#show", as: "article"
  get "article/:id/delete" => "articles#delete", as: "delete_article"
  get "article/:id/edit" => "articles#edit", as: "edit_article"
  put "article/:id/update" => "articles#update", as: "update_article"
  get "about" => "pages#about", as: "about_pages"
  get "contact"=> "pages#contact", as: "contact_pages"

  get "admin" =>"admin#index"


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  def fetch
    raise NotImplementedError
  end
end

app/models/user.rb
class User < ApplicationRecord



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def new
    Article.create(title: params[:title], description: params[:description], link: params[:link])
    redirect_to admin_urls
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def delete
    @article = Article.find(params[:id])
    @article.delete
    redirect_to admin_url
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.title= params[:title]
    @article.description= params[:description]
    @article.link= params[:link]
    @article.save
    redirect_to admin_url
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/index.html.erb
<div class="container">
 <div class="row">
   <%= link_to("create", articles_create_url) %>
 </div>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th>title</th>
    <th>last changed</th>
    <th>modify</th>
    <th>delete</th>
  </tr>
   </thead>
   <% Article.find_each do |ar| %>
   <tr>
     <th><%= ar.title %> </th>
     <th><%= time_ago_in_words(ar.updated_at) %></th>
     <th><%= link_to "edit", edit_article_url(ar.id) %></th>
     <th><%= link_to "delete", delete_article_url(ar.id) %></th>
   </tr>


   <% end %>
</table>
</div>

app/views/articles/create.html.erb
<div class="container">

  <%= form_tag articles_url, method: :POST do %>
    <div class="form-group">
      <label for="title">Title</label>
      <%= text_field_tag "title", " " , id: "title", class: "form-control"  %>
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <%= text_area_tag "description", " ", id: "description", class: "form-control"  %>
    </div>
    <div class="form-group">
      <label for="link">Link</label>
      <%= text_field_tag "link", " ",   id: "link", class: "form-control"  %>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  <% end %>

</div>

app/views/articles/edit.html.erb
<div class="container">

  <%= form_tag update_article_url(id: @article.id), method: :PUT do %>
    <div class="form-group">
      <label for="title">Title</label>
      <%= text_field_tag "title", @article.title, id: "title", class: "form-control"  %>
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <%= text_area_tag "description", @article.description, id: "description", class: "form-control"  %>
    </div>
    <div class="form-group">
      <label for="link">Link</label>
      <%= text_field_tag "link", @article.link, id: "link", class: "form-control"  %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>

</div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>

<body>

  <div class="container">

    <p> Good News </p>
    <% @articles.each do |article| %>
      <div class="row">
        <p>
          <%= article.title %>
        </p>
        <p>
          <%= article.link %>
        </p>
      </div>
      <% end %>

  </div>

</body>

</html>

app/views/articles/show.html.erb
<body>

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://static.pexels.com/photos/592658/pexels-photo-592658.jpeg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://static.pexels.com/photos/592658/pexels-photo-592658.jpeg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://static.pexels.com/photos/592658/pexels-photo-592658.jpeg" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

 </body>

app/views/home/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Ruda" rel="stylesheet">
<aside id="sticky-social">
    <ul>
        <li><a href="https://www.facebook.com/nicole.mayorga.714" class="entypo-facebook" target="_blank"><span>Facebook</span></a></li>
        <li><a href="#" class="entypo-twitter" target="_blank"><span>Twitter</span></a></li>
        <li><a href="#" class="entypo-instagrem" target="_blank"><span>Instagram</span></a></li>
        <li><a href="#" class="entypo-flickr" target="_blank"><span>Flickr</span></a></li>
        <li><a href="#" class="entypo-tumblr" target="_blank"><span>Tumblr</span></a></li>
    </ul>
</aside>

  <div class="container">
    <div class="row">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="https://static.pexels.com/photos/243971/pexels-photo-243971.jpeg" alt="First slide">
          </div>
          <div class="carousel-caption d-none d-md-block">
           <h3>“In order to carry a positive action we must develop here a positive vision.”</h3>
            <p>- Dalai Lama</p>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://static.pexels.com/photos/365067/pexels-photo-365067.jpeg" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://static.pexels.com/photos/612977/pexels-photo-612977.jpeg" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    </div>

    <div class="row">
      <ul id="nav_list" class="nav__menu">
        <li class="nav_item"><span class="label">Headlines</span></li>
        <li class="nav_item"><span class="label">World</span></li>
        <li class="nav_item"><span class="label">Nature</span></li>
        <li class="nav_item"><span class="label">People</span></li>
        <li class="nav_item"><span class="label">Animals</span></li>
        <li class="nav_item"><span class="label">Stories</span></li>
        <li class="nav_item"><span class="label">Countries</span></li>
      </ul>
    </div>

    <div class="row">
      <% Article.find_each do |ar| %>
      <div class="col-sm-6">
        <div class="card">
          <img class="card-img-top" src="/puppies.jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title"><%= ar.title %></h4>
            <p class="card-text"><%= ar.description || "no content" %></p>
            <a href="<%= ar.link %>" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Good News</title>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <div class="container">
     <a class="navbar-brand" href="#">Goodnews.</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">

       <ul class="navbar-nav">
         <li class="nav-item active">
           <%= link_to('home', root_path, class: "nav-link") %>
         </li>
         <li class="nav-item">
           <%= link_to('about', about_pages_path, class: "nav-link") %>
         </li>
         <li class="nav-item">
           <%= link_to('contact', contact_pages_path, class: "nav-link") %>
         </li>
       </ul>
       <ul class="navbar-nav ml-auto">

         <% if user_signed_in? || admin_signed_in? %>
         <li class="nav-item">
           <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
         </li>
         <% else %>
         <li class="nav-item">
           <%= link_to('Sign Up', new_user_registration_path, class: "nav-link") %>
         </li>
         <li class="nav-item">
           <%= link_to('Login', new_user_session_path, class: "nav-link") %>
         </li>
         <% end %>
       </ul>
   </div>
  </nav>



    <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<div class="container">
<h1>About</h1>

<br>
<br>

<p> Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
</p>
</div>

app/views/pages/contact.html.erb
<h1>Contact info here!</h1>